apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-init-sql
  labels:
    {{- include "calendar-app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    description: "This ConfigMap is used to initialize the MySQL database via the initdbScriptsConfigMap setting in the MySQL chart."
data:
  init.sql: |-
    -- Create events table if not exists
    CREATE TABLE IF NOT EXISTS events (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      date DATE NOT NULL
    );
    
    -- Insert some sample events
    INSERT INTO events (name, date) VALUES 
    ('Team Meeting', DATE_ADD(CURDATE(), INTERVAL 1 DAY)),
    ('Project Deadline', DATE_ADD(CURDATE(), INTERVAL 7 DAY)),
    ('Company Event', DATE_ADD(CURDATE(), INTERVAL 14 DAY)); 