apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calendar-app.fullname" . }}
  labels:
    {{- include "calendar-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "calendar-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "calendar-app.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.35.0-uclibc
          command: ['sh', '-c', 'until nc -z {{ .Release.Name }}-mysql.{{ .Release.Namespace }}.svc.cluster.local 3306; do echo "Waiting for MySQL..."; sleep 5; done;']
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: MYSQL_HOST
              value: "{{ .Release.Name }}-mysql.{{ .Release.Namespace }}.svc.cluster.local"
            - name: MYSQL_USER
              value: "{{ .Values.mysql.auth.username }}"
            - name: MYSQL_PASSWORD
              value: "{{ .Values.mysql.auth.password }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.mysql.auth.database }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.healthCheck.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthCheck.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.healthCheck.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthCheck.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.healthCheck.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.readinessProbe.periodSeconds }}
          {{- end }} 